export const customerActions = {
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
  CREATE_CUSTOMER_ERROR: 'CREATE_CUSTOMER_ERROR',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
  DELETE_CUSTOMER_ERROR: 'DELETE_CUSTOMER_ERROR',
  EDIT_CUSTOMER: 'EDIT_CUSTOMER',
  EDIT_NOTE_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',
  EDIT_CUSTOMER_ERROR: 'EDIT_CUSTOMER_ERROR',
  GET_ALL: 'GET_ALL',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_ERROR: 'GET_ALL_ERROR',
  GET_ONE: 'GET_BY_ID',
  GET_ONE_SUCCESS: 'GET_BY_ID_SUCCESS',
  GET_ONE_ERROR: 'GET_BY_ID_ERROR',
  CLEAR_CURRENT: 'CLEAR_CURRENT'
}
